# Execute on install-vm

- name: "Install {{ bstrp.name }}-VM"
  become: "true"
  become_user: "root"
  hosts: 127.0.0.1
  gather_facts: "false"
  vars_files:
    - "../vars/vars.yaml"
  vars:
    # - cpu: "{{ bstrp.cpu }}"
    # - ram: "{{ bstrp.ram }}"
    # - hostname: "{{ bstrp.hostname }}"
    # - ip: "{{ bstrp.ip }}"
    # - ignition_file: "{{ignition_filename_bootstrap}}"
 
  tasks:
# Erstelle Arbeitsverzeichnisse
    - name: "01 --- Create Working-Directories"
      file:
        path: "{{ item }}"
        state: "directory"
        recurse: "true"
      with_items:
        - "{{ dir_terraform }}{{ bstrp.hostname }}"
        - "{{ dir_terraform }}{{ masters[0].hostname }}"
        - "{{ dir_terraform }}{{ masters[1].hostname }}"
        - "{{ dir_terraform }}{{ masters[2].hostname }}"
        - "{{ dir_terraform }}{{ workers[0].hostname }}"
        - "{{ dir_terraform }}{{ workers[1].hostname }}"
        - "{{ dir_terraform }}{{ workers[2].hostname }}"

# Create tf-files
# Erstelle VM-Instanz Terraform "main.tf"-file
# main.tf
# Masters
    # - name: "02a --- Create main.tf - {{ masters[0].hostname }}"
    #   vars:
    #     - cpu: "{{ masters[0].cpu }}"
    #     - ram: "{{ masters[0].ram }}"
    #     - hostname: "{{ masters[0].hostname }}"
    #     - ip: "{{ masters[0].ip }}"
    #   template:
    #     src: "../99-jinja-templates/terraform/ocp-master-tf.j2"
    #     dest: "{{ dir_terraform }}{{ hostname }}/main.tf"

    - name: "02a --- Create main.tf - {{ masters[0].hostname }}"
      vars:
        - cpu: "{{ item.cpu }}"
        - ram: "{{ item.ram }}"
        - hostname: "{{ item.hostname }}"
        - ip: "{{ item.ip }}"
      template:
        src: "../99-jinja-templates/terraform/ocp-master-tf.j2"
        dest: "{{ dir_terraform }}{{ hostname }}/main.tf"
      with_items: "{{masters}}"


#     - name: "02b --- Create main.tf - {{ masters[1].hostname }}"
#       vars:
#         - cpu: "{{ masters[1].cpu }}"
#         - ram: "{{ masters[1].ram }}"
#         - hostname: "{{ masters[1].hostname }}"
#         - ip: "{{ masters[1].ip }}"
#       template:
#         src: "../99-jinja-templates/terraform/ocp-master-tf.j2"
#         dest: "{{ dir_terraform }}{{ hostname }}/main.tf"

#     - name: "02c --- Create main.tf - {{ masters[2].hostname }}"
#       vars:
#         - cpu: "{{ masters[2].cpu }}"
#         - ram: "{{ masters[2].ram }}"
#         - hostname: "{{ masters[2].hostname }}"
#         - ip: "{{ masters[2].ip }}"
#       template:
#         src: "../99-jinja-templates/terraform/ocp-master-tf.j2"
#         dest: "{{ dir_terraform }}{{ hostname }}/main.tf"

# # Workers
#     - name: "02d --- Create main.tf - {{ workers[0].hostname }}"
#       vars:
#         - cpu: "{{ workers[0].cpu }}"
#         - ram: "{{ workers[0].ram }}"
#         - hostname: "{{ workers[0].hostname }}"
#         - ip: "{{ workers[0].ip }}"
#       template:
#         src: "../99-jinja-templates/terraform/ocp-master-tf.j2"
#         dest: "{{ dir_terraform }}{{ hostname }}/main.tf"

#     - name: "02e --- Create main.tf - {{ workers[1].hostname }}"
#       vars:
#         - cpu: "{{ workers[1].cpu }}"
#         - ram: "{{ workers[1].ram }}"
#         - hostname: "{{ workers[1].hostname }}"
#         - ip: "{{ workers[1].ip }}"
#       template:
#         src: "../99-jinja-templates/terraform/ocp-master-tf.j2"
#         dest: "{{ dir_terraform }}{{ hostname }}/main.tf"

#     - name: "02f --- Create main.tf - {{ workers[2].hostname }}"
#       vars:
#         - cpu: "{{ workers[2].cpu }}"
#         - ram: "{{ workers[2].ram }}"
#         - hostname: "{{ workers[2].hostname }}"
#         - ip: "{{ workers[2].ip }}"
#       template:
#         src: "../99-jinja-templates/terraform/ocp-master-tf.j2"
#         dest: "{{ dir_terraform }}{{ hostname }}/main.tf"

# # # output.tf
# #     - name: "03 --- Create output.tf"
# #       template:
# #         src: "../99-jinja-templates/terraform/output.j2"
# #         dest: "{{ dir_terraform }}{{ masters[0].hostname }}/output.tf"
# # Masters
#     - name: "03a --- Create output.tf - {{ masters[0].hostname }}"
#       vars:
#         - cpu: "{{ masters[0].cpu }}"
#         - ram: "{{ masters[0].ram }}"
#         - hostname: "{{ masters[0].hostname }}"
#         - ip: "{{ masters[0].ip }}"
#       template:
#         src: "../99-jinja-templates/terraform/output.tf"
#         dest: "{{ dir_terraform }}{{ hostname }}/output.tf"

#     - name: "03b --- Create output.tf - {{ masters[1].hostname }}"
#       vars:
#         - cpu: "{{ masters[1].cpu }}"
#         - ram: "{{ masters[1].ram }}"
#         - hostname: "{{ masters[1].hostname }}"
#         - ip: "{{ masters[1].ip }}"
#       template:
#         src: "../99-jinja-templates/terraform/output.tf"
#         dest: "{{ dir_terraform }}{{ hostname }}/output.tf"

#     - name: "03c --- Create output.tf - {{ masters[2].hostname }}"
#       vars:
#         - cpu: "{{ masters[2].cpu }}"
#         - ram: "{{ masters[2].ram }}"
#         - hostname: "{{ masters[2].hostname }}"
#         - ip: "{{ masters[2].ip }}"
#       template:
#         src: "../99-jinja-templates/terraform/output.tf"
#         dest: "{{ dir_terraform }}{{ hostname }}/output.tf"

# # Workers
#     - name: "03d --- Create output.tf - {{ workers[0].hostname }}"
#       vars:
#         - cpu: "{{ workers[0].cpu }}"
#         - ram: "{{ workers[0].ram }}"
#         - hostname: "{{ workers[0].hostname }}"
#         - ip: "{{ workers[0].ip }}"
#       template:
#         src: "../99-jinja-templates/terraform/output.tf"
#         dest: "{{ dir_terraform }}{{ hostname }}/output.tf"

#     - name: "03e --- Create output.tf - {{ workers[1].hostname }}"
#       vars:
#         - cpu: "{{ workers[1].cpu }}"
#         - ram: "{{ workers[1].ram }}"
#         - hostname: "{{ workers[1].hostname }}"
#         - ip: "{{ workers[1].ip }}"
#       template:
#         src: "../99-jinja-templates/terraform/output.tf"
#         dest: "{{ dir_terraform }}{{ hostname }}/output.tf"

#     - name: "03f --- Create output.tf - {{ workers[2].hostname }}"
#       vars:
#         - cpu: "{{ workers[2].cpu }}"
#         - ram: "{{ workers[2].ram }}"
#         - hostname: "{{ workers[2].hostname }}"
#         - ip: "{{ workers[2].ip }}"
#       template:
#         src: "../99-jinja-templates/terraform/output.tf"
#         dest: "{{ dir_terraform }}{{ hostname }}/output.tf"




# # # vars.tf
# #     - name: "04 --- Create vars.tf"
# #       template:
# #         src: "../99-jinja-templates/terraform/vars-coreos-tf.j2"
# #         dest: "{{ dir_terraform }}{{ masters[0].hostname }}/vars.tf"
#     - name: "04a --- Create vars.tf - {{ masters[0].hostname }}"
#       vars:
#         - cpu: "{{ masters[0].cpu }}"
#         - ram: "{{ masters[0].ram }}"
#         - hostname: "{{ masters[0].hostname }}"
#         - ip: "{{ masters[0].ip }}"
#       template:
#         src: "../99-jinja-templates/terraform/vars-coreos-tf.j2"
#         dest: "{{ dir_terraform }}{{ hostname }}/vars.tf"

#     - name: "04b --- Create vars.tf - {{ masters[1].hostname }}"
#       vars:
#         - cpu: "{{ masters[1].cpu }}"
#         - ram: "{{ masters[1].ram }}"
#         - hostname: "{{ masters[1].hostname }}"
#         - ip: "{{ masters[1].ip }}"
#       template:
#         src: "../99-jinja-templates/terraform/vars-coreos-tf.j2"
#         dest: "{{ dir_terraform }}{{ hostname }}/vars.tf"

#     - name: "04c --- Create vars.tf - {{ masters[2].hostname }}"
#       vars:
#         - cpu: "{{ masters[2].cpu }}"
#         - ram: "{{ masters[2].ram }}"
#         - hostname: "{{ masters[2].hostname }}"
#         - ip: "{{ masters[2].ip }}"
#       template:
#         src: "../99-jinja-templates/terraform/vars-coreos-tf.j2"
#         dest: "{{ dir_terraform }}{{ hostname }}/vars.tf"

# # Workers
#     - name: "04d --- Create vars.tf - {{ workers[0].hostname }}"
#       vars:
#         - cpu: "{{ workers[0].cpu }}"
#         - ram: "{{ workers[0].ram }}"
#         - hostname: "{{ workers[0].hostname }}"
#         - ip: "{{ workers[0].ip }}"
#       template:
#         src: "../99-jinja-templates/terraform/vars-coreos-tf.j2"
#         dest: "{{ dir_terraform }}{{ hostname }}/vars.tf"

#     - name: "04e --- Create vars.tf - {{ workers[1].hostname }}"
#       vars:
#         - cpu: "{{ workers[1].cpu }}"
#         - ram: "{{ workers[1].ram }}"
#         - hostname: "{{ workers[1].hostname }}"
#         - ip: "{{ workers[1].ip }}"
#       template:
#         src: "../99-jinja-templates/terraform/vars-coreos-tf.j2"
#         dest: "{{ dir_terraform }}{{ hostname }}/vars.tf"

#     - name: "04f --- Create vars.tf - {{ workers[2].hostname }}"
#       vars:
#         - cpu: "{{ workers[2].cpu }}"
#         - ram: "{{ workers[2].ram }}"
#         - hostname: "{{ workers[2].hostname }}"
#         - ip: "{{ workers[2].ip }}"
#       template:
#         src: "../99-jinja-templates/terraform/vars-coreos-tf.j2"
#         dest: "{{ dir_terraform }}{{ hostname }}/vars.tf"

# # Execute terraform
# # Erzeuge die virtuelle Maschine
#     - name: "05a --- Terraform - Create virtual machine {{ bstrp.hostname }}"
#       raw: "cd {{ dir_terraform }}{{ bstrp.hostname }} && /usr/local/bin/terraform init && /usr/local/bin/terraform apply -auto-approve"
#     - name: "05b --- Terraform - Create virtual-machine {{ masters[0].hostname }}"
#       raw: "cd {{ dir_terraform }}{{ masters[0].hostname }} && /usr/local/bin/terraform init && /usr/local/bin/terraform apply -auto-approve"
#     - name: "05c --- Terraform - Create virtual-machine {{ masters[1].hostname }}"
#       raw: "cd {{ dir_terraform }}{{ masters[1].hostname }} && /usr/local/bin/terraform init && /usr/local/bin/terraform apply -auto-approve"
#     - name: "05d --- Terraform - Create virtual-machine {{ masters[2].hostname }}"
#       raw: "cd {{ dir_terraform }}{{ masters[2].hostname }} && /usr/local/bin/terraform init && /usr/local/bin/terraform apply -auto-approve"
#     - name: "05e --- Terraform - Create virtual-machine {{ workers[0].hostname }}"
#       raw: "cd {{ dir_terraform }}{{ workers[0].hostname }} && /usr/local/bin/terraform init && /usr/local/bin/terraform apply -auto-approve"
#     - name: "05f --- Terraform - Create virtual-machine {{ workers[1].hostname }}"
#       raw: "cd {{ dir_terraform }}{{ workers[1].hostname }} && /usr/local/bin/terraform init && /usr/local/bin/terraform apply -auto-approve"
#     - name: "05g --- Terraform - Create virtual-machine {{ workers[2].hostname }}"
#       raw: "cd {{ dir_terraform }}{{ workers[2].hostname }} && /usr/local/bin/terraform init && /usr/local/bin/terraform apply -auto-approve"


# insert DHCP-entries


# create PXE-files


# insert DNS-entries


