# Execute on install-vm

- name: "Install {{ bstrp.name }}-VM"
  become: "true"
  become_user: "root"
  hosts: 127.0.0.1
  gather_facts: "false"
  vars_files:
    - "../vars/vars.yaml"
  vars:
    # - cpu: "{{ bstrp.cpu }}"
    # - ram: "{{ bstrp.ram }}"
    # - hostname: "{{ bstrp.hostname }}"
    # - ip: "{{ bstrp.ip }}"
    # - ignition_file: "{{ignition_filename_bootstrap}}"
 
  tasks:
# Erstelle Arbeitsverzeichnisse
    - name: "01 --- Create Working-Directories"
      file:
        path: "{{ item }}"
        state: "directory"
        recurse: "true"
      with_items:
        - "{{ dir_terraform }}{{ bstrp.hostname }}"
        - "{{ dir_terraform }}{{ masters[0].hostname }}"
        - "{{ dir_terraform }}{{ masters[1].hostname }}"
        - "{{ dir_terraform }}{{ masters[2].hostname }}"
        - "{{ dir_terraform }}{{ workers[0].hostname }}"
        - "{{ dir_terraform }}{{ workers[1].hostname }}"
        - "{{ dir_terraform }}{{ workers[2].hostname }}"

# Create tf-files
# Erstelle VM-Instanz Terraform "main.tf"-file
# main.tf
# Masters / Workers
    - name: "02a --- Create main.tf"
      vars:
        - cpu: "{{ item.cpu }}"
        - ram: "{{ item.ram }}"
        - hostname: "{{ item.hostname }}"
        - ip: "{{ item.ip }}"
        - disk: "{{ item.disk }}"
      template:
        src: "../99-jinja-templates/terraform/ocp-master-tf.j2"
        dest: "{{ dir_terraform }}{{ hostname }}/main.tf"
      with_items: 
        - "{{ masters }}"
        - "{{ workers }}"
        - "{{ bstrp }}"

# output.tf
# Masters / Workers
    - name: "03a --- Create output.tf"
      vars:
        - cpu: "{{ item.cpu }}"
        - ram: "{{ item.ram }}"
        - hostname: "{{ item.hostname }}"
        - ip: "{{ item.ip }}"
        - disk: "{{ item.disk }}"
      template:
        src: "../99-jinja-templates/terraform/output.j2"
        dest: "{{ dir_terraform }}{{ hostname }}/output.tf"
      with_items: 
        - "{{ masters }}"
        - "{{ workers }}"
        - "{{ bstrp }}"

# vars.tf
    - name: "04a --- Create vars.tf"
      vars:
        - cpu: "{{ item.cpu }}"
        - ram: "{{ item.ram }}"
        - hostname: "{{ item.hostname }}"
        - ip: "{{ item.ip }}"
        - disk: "{{ item.disk }}"
      template:
        src: "../99-jinja-templates/terraform/vars-coreos-tf.j2"
        dest: "{{ dir_terraform }}{{ hostname }}/vars.tf"
      with_items: 
        - "{{ masters }}"
        - "{{ workers }}"
        - "{{ bstrp }}"


# # Execute terraform
# # Erzeuge die virtuelle Maschine
    - name: "05 --- Terraform - Create virtual machine"
      vars:
        hostname: "{{ item.hostname }}"
      raw: "cd {{ dir_terraform }}{{ hostname }} && /usr/local/bin/terraform init && /usr/local/bin/terraform apply -auto-approve"      
      with_items: 
        - "{{ masters }}"
        - "{{ workers }}"
        - "{{ bstrp }}"

    - name: "06 --- Retrieve mac-address from created virtual machines"
      raw: "cd {{ dir_terraform }}{{ item.hostname }} && /usr/local/bin/terraform output -json | jq '.[\"mac-address\"].value' | sed -e 's|\"||g'"
      register: mac
      with_items:
        - "{{ masters }}"
        - "{{ workers }}"
        - "{{ bstrp }}"
      tags:
        - getmac

    - debug: var=mac.results
      tags:
        - getmac

# insert DHCP-entries
    - name: "07 --- Add DHCP-entry to /etc/dhcp/dhcpd.conf"
      become: "true"
      become_user: "root"
      vars:
        hostname: "{{ mac.results[item].item.hostname }}"
        ip: "{{ mac.results[item].item.ip }}"
      lineinfile:
        path: "/etc/dhcp/dhcpd.conf"
        line: "host {{ hostname }} { server-name \"{{ bastion.ip }}\"; next-server {{ bastion.ip }}; filename \"{{ boot_script }}\"; hardware ethernet {{ mac.results[item].stdout | trim }}; fixed-address {{ip}}; option host-name \"{{hostname}}\"; }"
      with_items:
        - 0
        - 1
        - 2
        - 3
        - 4
        - 5
        - 6
      delegate_to: "{{bastion.ip}}"
      notify: "restart dhcpd"
      tags:
        - getmac


# create PXE-files
    - name: "08 --- PXE - (MASTERS) - Create mac-address-files in {{dir_tftproot}}"
      become: "true"
      become_user: "root"
      vars:
        ignition_file: "{{ignition_filename_master}}"
        hostname: "{{ mac.results[item].item.hostname }}"
      template:
        src: "../99-jinja-templates/pxe/pxelinux.cfg.j2"
        dest: "{{dir_tftproot}}01-{{ mac.results[item].stdout | trim | regex_replace(':', '-')}}"
        mode: "0755"
        owner: "dnsmasq"
        group: "wheel"
      with_items:
        - 0
        - 1
        - 2
      delegate_to: "{{ bastion.ip }}"
      tags:
        - getmac

    - name: "09 --- PXE - (WORKERS) - Create mac-address-files in {{dir_tftproot}}"
      become: "true"
      become_user: "root"
      vars:
        ignition_file: "{{ignition_filename_worker}}"
        hostname: "{{ mac.results[item].item.hostname }}"
      template:
        src: "../99-jinja-templates/pxe/pxelinux.cfg.j2"
        dest: "{{dir_tftproot}}01-{{ mac.results[item].stdout | trim | regex_replace(':', '-')}}"
        mode: "0755"
        owner: "dnsmasq"
        group: "wheel"
      with_items:
        - 3
        - 4
        - 5
      delegate_to: "{{ bastion.ip }}"
      tags:
        - getmac

    - name: "10 --- PXE - (BOOTSTRAP) - Create mac-address-files in {{dir_tftproot}}"
      become: "true"
      become_user: "root"
      vars:
        ignition_file: "{{ignition_filename_bootstrap}}"
        hostname: "{{ mac.results[item].item.hostname }}"
      template:
        src: "../99-jinja-templates/pxe/pxelinux.cfg.j2"
        dest: "{{dir_tftproot}}01-{{ mac.results[item].stdout | trim | regex_replace(':', '-')}}"
        mode: "0755"
        owner: "dnsmasq"
        group: "wheel"
      with_items:
        - 6
      delegate_to: "{{ bastion.ip }}"
      tags:
        - getmac

# insert DNS-entries


