- name: "Playbook - OpenShift-Installation - wait-for bootstrap to complete"
  become: "true"
  gather_facts: "false"
  hosts: "{{bastion.ip}}"
  tasks:
    - name: "Wait for Installation to complete"
      raw: "openshift-install --dir={{dir_install_config}} wait-for install-complete"
