---
- hosts: "{{bastion.ip}}"  
  become: yes
  gather_facts: "false"
  vars_files:
    - "../vars/vars.yaml"
  tasks:
    - import_tasks: "tasks/01_prerequisites.yml"
    - import_tasks: "tasks/02_nfs_mount.yml"
    - import_tasks: "tasks/04_prepare_tools.yml"
    - import_tasks: "tasks/05_dnsmasq_config.yml"
<<<<<<< HEAD
    - import_tasks: "tasks/06_prepare_install_config.yml"
    - import_tasks: "tasks/07_network_boot_config.yml"
    - import_tasks: "tasks/08_manifest_ignition.yml"
    #- import_tasks: "../ocp-master-worker-nodes/01-create-terraform-main-tf.yaml"

=======
    #- import_tasks: "tasks/06_prepare_install_config.yml"
    - import_tasks: "tasks/07_network_boot_config.yml"
    #- import_tasks: "tasks/08_manifest_ignition.yml"
    #- import_tasks: "../ocp-master-worker-nodes/01-create-terraform-main-tf.yaml"

    # Disable Firewalld
    - name: "Disable Firewalld"
      systemd:
        name: "firewalld"
        state: "stopped"
        enabled: "no"

>>>>>>> dpg-openshift
  handlers:
    - import_tasks: handlers.yml 
