---
- name: "{{ lookup('pipe','date \"+%Y-%m-%d %H-%M-%S\"') }} | Playbook - Configure the load-balancer"
  hosts: "{{ lb.ip }}"
  become: "true"
  gather_facts: "false"
  vars_files:
    - "../vars/vars.yaml"
  tasks:
    - name: "118 - ssh-copy-id as user-root to {{lb.ip}}"
      become: "true"
      become_user: "root"
      raw: "sshpass -f '/root/rootpassword' ssh-copy-id -i /root/.ssh/id_rsa -o StrictHostKeyChecking=no root@{{lb.ip}}"
      delegate_to: "localhost"

    - name: "119 - Install haproxy-software and policycoreutils-python"
      yum:
        name: 
          - "haproxy"
          - "policycoreutils-python-utils"
          - "chrony.x86_64"
        state: "present"

# Disable Firewalld
    - name: "120 - Disable Firewalld"
      systemd:
        name: "firewalld"
        state: "stopped"
        enabled: "no"

    - name: "121 - Render haproxy-template for load-balancer-vm"
      template:
        src: "../99-jinja-templates/haproxy/haproxy.cfg.j2"
        dest: "/etc/haproxy/haproxy.cfg"
        owner: "root"
        group: "root"
        mode: "0644"
        force: "true"
        validate: "/usr/sbin/haproxy -f %s -c -q"
      notify:
        - restart haproxy

    - name: "122 - SELinux - Check Status"
      command: "/usr/sbin/getenforce"
      register: "getenforce_res"

    - name: "123 - Configure SELinux with enforcing mode"
      seport:
        ports: "6443,22623"
        proto: "tcp"
        setype: "commplex_main_port_t"
        state: "present"
      when: getenforce_res.stdout == 'Enforcing'

    - name: "124 - Start and enable service haproxy"
      systemd:
        name: "haproxy"
        state: "started"
        enabled: "true"

  handlers:
    - name: "restart haproxy"
      systemd:
        name: "haproxy"
        state: "restarted"
...