- name: "Install-VM"
  hosts: 127.0.0.1
  gather_facts: "false"
  vars:
    hostname: "patrick-vm-01"
    dir_tftproot: "/tftproot/pxelinux.cfg/"
    vm_type: "worker"
    ip: "10.0.249.111"
  tasks:
    - name: "01 --- Retrieve mac-address from created virtual machine"
      raw: "terraform output -json | jq '.[\"mac-address\"].value' | sed -e 's|\"||g'"
      register: mac

    - name: "01 --- Delete pxelinux-config-file on pxe-server"
      become: "true"
      become_user: "root"
      raw: "rm -f {{dir_tftproot}}01-{{ mac.stdout | trim | regex_replace(':', '-')}}"
      delegate_to: pxe-server

    - name: "02 --- Remove entry from dnsmasq.conf"
      become: "true"
      become_user: "root"
      lineinfile:
        path: "/etc/dnsmasq.conf"
        line: "dhcp-host={{ mac.stdout | trim }},{{hostname}},{{ ip }},set:ocp43"
        state: "absent"
      delegate_to: pi
      notify: 
        - "restart dnsmasq"


    - name: "03 --- Remove entry from dnsmasq.conf"
      become: "true"
      become_user: "root"
      lineinfile:
        path: "/etc/dnsmasq.conf"
        line: "address=/{{hostname}}.ocp43-patrick.home.local/{{ ip }}"
        state: "absent"
      delegate_to: pi
      notify: 
        - "restart dnsmasq"
    
    - name: "04 --- Delete virtual machine with terraform"
      raw: "terraform init && terraform destroy -auto-approve"

  handlers:
    - name: "restart dnsmasq"
      become: "true"
      become_user: "root"
      service:
        name: dnsmasq
        state: restarted
      delegate_to: pi
