- name: "Install-VM"
  hosts: 127.0.0.1
  gather_facts: "false"
  vars:
    hostname: "patrick-vm-01"
    dir_tftproot: "/tftproot/pxelinux.cfg/"
    vm_type: "worker"
    ip: "10.0.249.111"
    domain: "ocp43-patrick.home.local"
    cpu: "1"
    ram: "1024"
    vsphere_general_disksize: "120"
    boot_delay: "60000"
    dir_root: "/opt/sva/"
    dir_terraform: "{{dir_root}}terraform/"
    dir_terraform_modules: "{{dir_terraform}}modules/"
    dir_terraform_module_vm: "{{dir_terraform_modules}}vm-vsphere/"
    dir_vmware: "/dc-home/vm/spielwiese"
    dir_nfs_root: "/mnt/sva/"
    dir_mounted_kickstart_configs: "kickstart-configs/"
    vsphere_server: "vcenter.home.local"
    vsphere_user: "administrator@home.local"
    vsphere_pass: "Test1234!"
    nfs_server: "nas.home.local"
    nfs_mount_path: "/volume1/nfs-iso/"
    nfs_software_folder: "/volume1/nfs-iso/downloaded-iso/linux/"
    nfs_kickstart_folder: "/volume1/nfs-iso/kickstart-configs/"
    iso_centos77: "CentOS-7-x86_64-DVD-1908.iso"
    pxe_vmlinux_kernel: "kernels_initrd/centos77/vmlinuz"
    pxe_initrd_image: "kernels_initrd/centos77/initrd.img"
    ntp_server: "router.home.local"
    kickstart_file: "{{hostname}}.cfg"
  tasks:
    - name: "01 --- Retrieve mac-address from created virtual machine"
      raw: "cd {{ dir_terraform }}{{ hostname }} && terraform output -json | jq '.[\"mac-address\"].value' | sed -e 's|\"||g'"
      register: mac

    - name: "01 --- Delete pxelinux-config-file on pxe-server"
      become: "true"
      become_user: "root"
      raw: "rm -f {{dir_tftproot}}01-{{ mac.stdout | trim | regex_replace(':', '-')}}"
      delegate_to: pxe-server

    - name: "02 --- Remove entry from dnsmasq.conf"
      become: "true"
      become_user: "root"
      lineinfile:
        path: "/etc/dnsmasq.conf"
        line: "dhcp-host={{ mac.stdout | trim }},{{hostname}},{{ ip }},set:ocp43"
        state: "absent"
      delegate_to: pi
      notify: 
        - "restart dnsmasq"


    - name: "03 --- Remove entry from dnsmasq.conf"
      become: "true"
      become_user: "root"
      lineinfile:
        path: "/etc/dnsmasq.conf"
        line: "address=/{{hostname}}.ocp43-patrick.home.local/{{ ip }}"
        state: "absent"
      delegate_to: pi
      notify: 
        - "restart dnsmasq"
    
    - name: "04 --- Delete virtual machine with terraform"
      raw: "cd {{ dir_terraform }}{{ hostname }} && terraform init && terraform destroy -auto-approve"
#    - name: "05 --- Delete folder {{ dir_terraform }}{{ hostname }}"
#      raw: "rm -rf {{ dir_terraform }}{{ hostname }}"

  handlers:
    - name: "restart dnsmasq"
      become: "true"
      become_user: "root"
      service:
        name: dnsmasq
        state: restarted
      delegate_to: pi
