- name: "{{ lookup('pipe','date \"+%Y-%m-%d %H-%M-%S\"') }} | Playbook - UnInstall everything"
  become: "true"
  become_user: "root"
  hosts: 127.0.0.1
  gather_facts: "false"
  vars_files:
    - "../vars/vars.yaml"
  tasks:
    
# Lösche die virtuelle Maschine - Bastion
    - name: "999a --- Delete virtual machine ({{ bastion.hostname }}) with terraform"
      raw: "cd {{ dir_terraform }}{{ bastion.hostname }} && /usr/local/bin/terraform destroy -auto-approve"

# Lösche die virtuelle Maschine - Load-Balancer
    - name: "999b --- Delete virtual machine ({{ bastion.hostname }}) with terraform"
      raw: "cd {{ dir_terraform }}{{ lb.hostname }} && /usr/local/bin/terraform destroy -auto-approve"

# Lösche die virtuelle Maschine - Registry
    - name: "999c --- Delete virtual machine ({{ bastion.hostname }}) with terraform"
      raw: "cd {{ dir_terraform }}{{ registry.hostname }} && /usr/local/bin/terraform destroy -auto-approve"

# Lösche die virtuelle Maschine - Router
    - name: "999d --- Delete virtual machine ({{ bastion.hostname }}) with terraform"
      raw: "cd {{ dir_terraform }}{{ router.hostname }} && /usr/local/bin/terraform destroy -auto-approve"

# Lösche die virtuellen Maschinen - OpenShift-Nodes
    - name: "999e --- Delete virtual machines OpenShift-Nodes with terraform"
      raw: "cd {{ dir_terraform }}{{ clustername }}-nodes/ && /usr/local/bin/terraform init && /usr/local/bin/terraform destroy -auto-approve"

# Lösche Arbeitsverzeichnisse
    - name: "999f --- Delete Working-Directories"
      file:
        path: "{{ item }}"
        state: "absent"
        #recurse: "true"
      with_items:
        - "{{ dir_terraform }}{{ bastion.hostname }}"
        - "{{ dir_terraform }}{{ lb.hostname }}"
        - "{{ dir_terraform }}{{ registry.hostname }}"
        - "{{ dir_terraform }}{{ router.hostname }}"
        - "{{ dir_terraform }}{{ clustername }}-nodes"
