- name: "Kubectl"
  hosts: localhost
  tasks:
  - name: "Create a Service for nginx"
    k8s:
      state: absent
      definition:
        apiVersion: v1
        kind: Service
        metadata:
          name: web
          namespace: test
          labels:
            app: nginx
            service: web
        spec:
          selector:
            app: nginx
          ports:
          - protocol: TCP
            targetPort: 80
            name: port-8000-tcp
            port: 80