---
# Dieses Playbook erstellt die Arbeitsverzeichnisse auf dem Bastion-Host
- name: "### --- 01 - Create SSH-Connection to {{bastion.hostname}}"
  command: "sshpass -f '/root/rootpassword' ssh-copy-id -i /root/.ssh/id_rsa -o StrictHostKeyChecking=no {{bastion.hostname}}"
  delegate_to: "localhost"

- name: "02 - Copy password-file  to /root/"
  copy:
    src: "{{rootpw}}"
    dest: "{{rootpw}}"

- name: "01 - Install necassary software programs"
  become: "true"
  yum:
    name:
      - epel-release
      - centos-release-ansible-29.noarch
      - ansible.noarch
      - git
      - sshpass
      - wget.x86_64
      - jq.x86_64
      - podman.x86_64
      - skopeo.x86_64
      - nfs-utils.x86_64
      - unzip
    state: "present"



- name: "03 - Create SSH-Keypair"
  raw: "ssh-keygen -q -t rsa -N '' -f /root/.ssh/{{key_to_nodes_name}} <<<y 2>&1 >/dev/null"

- name: "04 - Create SSH-Connection on {{bastion.hostname}} itself"
  command: "sshpass -f '{{rootpw}}' ssh-copy-id -i /root/.ssh/{{key_to_nodes_name}} -o StrictHostKeyChecking=no localhost"

- name: "05 - Create working directories" 
  file:
    path: "{{ item }}"
    owner: root
    group: root
    mode: '0755'
    state: directory
    recurse: true
  with_items:
    - "{{ dir_root }}"
    - "{{ dir_tools }}"
    - "{{ dir_cluster }}"
    - "{{ dir_install_config }}"
    - "{{ dir_tftp_root }}"
    - "{{ dir_http_server }}"
    - "{{ dir_mnt }}"
    - "{{ dir_tftp_root }}{{ dir_coreos_files }}"
    - "{{ dir_terraform }}"
    - "{{ dir_backup }}"
    - "{{ dir_backup_manifest_files }}"
    - "{{ dir_backup_ignition_files }}"
    - "{{ dir_backup_ssh_keys }}"
    - "{{ dir_backup_tftp }}"
    - "{{ dir_backup_install_config }}"
    - "{{ dir_backup_dnsmasq }}"

# 21.09.2020 - New Feature to backup the SSH-Key-Folder-Content
- name: "06 - Backup SSH-Keys to /opt/sva/backup"
  command: cp "{{ dir_key_to_nodes }}{{ item }}" "{{ dir_backup_ssh_keys }}"
  with_items:
    - "{{ key_to_nodes_name }}"
    - "{{ key_to_nodes_name }}.pub"

- name: "07 - Copy CoreOS-Images to tftproot"
  copy:
    src: "{{item}}"
    dest: "{{ dir_tftp_root }}{{ dir_coreos_files }}"  
  loop:
    - "{{ dir_downloaded_images }}{{file_coreos_kernel}}"
    - "{{ dir_downloaded_images }}{{file_coreos_initrd}}"
    #- "{{ dir_downloaded_images }}{{file_coreos_raw_gz}}"
  tags:
    - test

