---
# Dieses Playbook erstellt die Arbeitsverzeichnisse auf dem Bastion-Host
- name: "00 - Copy file to /root-Home"
  copy:
    src: "/root/rootpassword"
    dest: "/root/rootpassword"

- name: "### --- 01 - Run 00_create_ssh_keys.sh"
  command: "sshpass -f '/root/rootpassword' ssh-copy-id -i /root/.ssh/id_rsa -o StrictHostKeyChecking=no root@localhost"
  tags:
    - debug


- name: "### --- 02 - Create working directories" 
  file:
    path: "{{ item }}"
    owner: root
    group: root
    mode: '0755'
    state: directory
    recurse: true
  with_items:
    - "{{ dir_root }}"
    - "{{ dir_tools }}"
    - "{{ dir_cluster }}"
    - "{{ dir_install_config }}"
    - "{{ dir_tftp_root }}"
    - "{{ dir_http_server }}"
    - "{{ dir_mnt }}"
    - "{{ dir_tftp_root }}{{ dir_coreos_files }}"
    - "{{ dir_terraform }}"
    - "{{ dir_backup }}"
    - "{{ dir_backup_manifest_files }}"
    - "{{ dir_backup_ignition_files }}"
    - "{{ dir_backup_ssh_keys }}"
    - "{{ dir_backup_tftp }}"
    - "{{ dir_backup_install_config }}"
    - "{{ dir_backup_dnsmasq }}"

# 21.09.2020 - New Feature to backup the SSH-Key-Folder-Content
- name: "### --- 03 - Backup SSH-Keys to /opt/sva/backup"
  command: cp "{{ dir_key_to_nodes }}{{ item }}" "{{ dir_backup_ssh_keys }}"
  with_items:
    - "{{ key_to_nodes_name }}"
    - "{{ key_to_nodes_name }}.pub"



