---
- name: "### --- 31 - Allow incoming connections to the tftp service in the firewall"
  firewalld:
    service: tftp
    permanent: yes
    state: enabled


- name: "### --- 32 - Make sure pxelinux.0 and menu.c32 exists in '{{ dir_tftp_root }}'"
  copy:
    src: "/usr/share/syslinux/{{ item }}"
    dest: "{{ dir_tftp_root }}{{ item }}"
    owner: root
    group: root
    mode: '0644'
  with_items: 
    - 'pxelinux.0'
    - 'menu.c32'

- name: "### --- 33 - Make sure folder '{{ dir_tftp_root }}pxelinux.cfg/' exists"
  file:
    path: "{{ dir_tftp_root }}pxelinux.cfg"
    state: directory
    owner: root
    group: root
    mode: '0755'

- name: "### --- 34 - Render pxelinux.cfg from templates for masters"
  template:
    src: templates/pxelinux.cfg.j2
    dest: "{{ dir_tftp_root }}pxelinux.cfg/01-{{ item.mac | regex_replace(':','-') }}"
    owner: root
    group: root
    mode: '0755'
  vars: 
    ignition_file: master.ign
  with_items: "{{ masters }}"

- name: "### --- 35 - Render pxelinux.cfg from templates for workers"
  template:
    src: templates/pxelinux.cfg.j2
    dest: "{{ dir_tftp_root }}pxelinux.cfg/01-{{ item.mac | regex_replace(':','-') }}"
    owner: root
    group: root
    mode: '0755'
  vars: 
    ignition_file: worker.ign
  with_items: "{{ workers }}"

- name: "### --- 36 - Render pxelinux.cfg from templates for bootstrap"
  template:
    src: templates/pxelinux.cfg.j2
    dest: "{{ dir_tftp_root }}pxelinux.cfg/01-{{ item.mac | regex_replace(':','-') }}"
    owner: root
    group: root
    mode: '0755'
  vars: 
    ignition_file: bootstrap.ign
  with_items: 
    - "{{ bstrp }}"

- name: "### --- 37 - Start and enable HTTP server"
  service:
    name: httpd
    state: started
    enabled: yes

# 21.09.2020 - New Feature to backup the TFTP-Folder-Content
- name: "### --- 38 - Backup TFTP-Folder to /opt/sva/backup"
  command: cp -r  "{{ dir_tftp_root }}" "{{ dir_backup_tftp }}"