---
# Execute on install-vm
- hosts: "{{ bastion.ip }}"
  vars_files:
    - "../vars/vars.yaml"
  tasks:
    # - import_tasks: "tasks/10-ntp-chronyd.yaml"
    # - import_tasks: "tasks/11-install-spectrum-scale-cnsa.yaml"
    - import_tasks: "tasks/12-deploy-csi-driver.yaml"

...