---
# Execute on install-vm
- hosts: "{{ bastion.ip }}"
  vars_files:
    - "../vars/vars.yaml"
  tasks:
    - name: "Execution of post-installation-task after an ocp-installation"
        - import_tasks: tasks/10-ntp-chronyd.yaml
...