---
# Execute on install-vm
- hosts: "{{ bastion.ip }}"
  # debugger: on_skipped
  vars_files:
    - "../vars/vars.yaml"
  tasks:
    # - import_tasks: "tasks/10-ntp-chronyd.yaml"
    # - import_tasks: "tasks/11-install-spectrum-scale-cnsa.yaml"
    - import_tasks: "tasks/12-deploy-csi-driver.yaml"
    - import_tasks: "tasks/13-deploy-spectrum-scale-storageclass.yaml"
    - import_tasks: "tasks/14-deploy-spectrum-scale-snapshotclass.yaml" 
...