# Start with Router-vm
- import_playbook: "../00-install-and-configure-router-vm/01-playbook-install-router-vm.yaml"
- name: "Wait for {{ router.hostname }} to become available"
  gather_facts: "false"
  vars_files:
    - "../vars/vars.yaml"
  hosts: "{{ router.ip }}"
  tasks:
    - name: "Wait 300 seconds, check each 10 seconds"
      wait_for_connection:
        delay: 10
        timeout: 300
- import_playbook: "../00-install-and-configure-router-vm/02-playbook-configure-router-vm.yaml"

# Start Bastion-Host
- import_playbook: "../01-install-and-configure-bastion-host-vm/01-playbook-install-bastion-vm.yaml"
- name: "Wait for {{ bastion.hostname }} ({{ bastion.hostname }}) to become available"
  gather_facts: "false"
  vars_files:
    - "../vars/vars.yaml"
  hosts: "{{ bastion.ip }}"
  tasks:
    - name: "Wait 300 seconds, check each 10 seconds"
      wait_for_connection:
        delay: 10
        timeout: 300
- import_playbook: "../01-install-and-configure-bastion-host-vm/02-playbook-configure-bastion-vm.yaml"
