- name: "Playbook - Install the Registry-VM"
  become: "true"
  become_user: "root"
  hosts: 127.0.0.1
  gather_facts: "false"
  vars_files:
    - "../vars/vars.yaml"
  vars:
    - cpu: "{{ registry.cpu }}"
    - ram: "{{ registry.ram }}"
    - hostname: "{{ registry.hostname }}"
    - ip: "{{ registry.ip }}"
    - kickstart_file: "{{ registry.hostname }}.cfg"
 
  tasks:
    # Check if Folder exists
    - name: "00 - Prüfe, ob Ordner {{ dir_terraform }}{{ registry.hostname }} existiert"
      stat:
        path: "{{ dir_terraform }}{{ registry.hostname }}"
      register: folder_details
      ignore_errors: yes

    - name: "Folder exists: {{ dir_terraform }}{{ registry.hostname }}"
      debug:
        msg: "The folder {{ dir_terraform }}{{ registry.hostname }} exists. Please check, if Host: {{ registry.hostname }} is already installed."
      when: folder_details.stat.isdir is defined and folder_details.stat.isdir

    - meta: end_play
      when: folder_details.stat.exists == true

# Erstelle Arbeitsverzeichnisse
    - name: "78 --- Create Working-Directories"
      file:
        path: "{{ item }}"
        state: "directory"
        recurse: "true"
      with_items:
        - "{{ dir_root }}"
<<<<<<< HEAD
        # - "{{ dir_terraform }}"
        - "{{ dir_terraform }}{{ registry.hostname }}"
        # - "{{ dir_terraform_module_vm }}"
      tags:
        - create

    # - name: "02 --- Create Working-Directories with sudo"
    #   file:
    #     path: "{{ item }}"
    #     state: "directory"
    #     recurse: "true"
    #   with_items:
    #     - "{{ dir_nfs_root }}"
    #   tags:
    #     - create

# Install some Software
    # - name: "03 --- Installiere nfs-utils.x86_64"
    #   yum:
    #     name: nfs-utils.x86_64
    #     state: present
    # - name: "04 --- Installiere libnfs-utils.x86_64"
    #   yum:
    #     name: libnfs-utils.x86_64
    #     state: present

# Prüfe, ob die IP-Adresse bereits in /etc/dnsmasq.conf existiert.
    # - name: "05 --- Check, if IP-Address {{ registry.ip }} exists in /etc/dnsmasq.conf"
    #   command: "grep \"{{ registry.ip }}\" /etc/dnsmasq.conf"
    #   register: checkmyconf
    #   check_mode: no
    #   ignore_errors: yes
    #   changed_when: no
    #   delegate_to: "pi"
    #   tags:
    #     - checker

    # - name: "06 --- If /etc/dnsmasq.conf contains {{ registry.ip }}, Stop Ansible-Playbook"
    #   debug: msg="Die IP-Adresse {{ registry.ip }} existiert bereits in /etc/dnsmasq.conf!"
    #   when: checkmyconf.rc == 0
    #   tags:
    #     - checker

# Prüfe, ob der Hostname {{registry.hostname}} bereits in /etc/dnsmasq.conf existiert.
    # - name: "07 --- Check, if IP-Address {{ registry.hostname }} exists in /etc/dnsmasq.conf"
    #   command: "grep \"{{ registry.hostname }}\" /etc/dnsmasq.conf"
    #   register: checkmyconf2
    #   check_mode: no
    #   ignore_errors: yes
    #   changed_when: no
    #   delegate_to: "pi"
    #   tags:
    #     - checker

    # - name: "08 --- If /etc/dnsmasq.conf contains {{ registry.hostname }}, Stop Ansible-Playbook"
    #   debug: msg="Der Hostname {{ registry.hostname }} existiert bereits in /etc/dnsmasq.conf!"
    #   when: checkmyconf2.rc == 0
    #   tags:
    #     - checker

# Beende das Playbook, wenn die IP-Adresse bereits in /etc/dnsmasq.conf existiert
    # - meta: end_play
    #   when: checkmyconf.rc == 0
# Beende das Playbook, wenn die IP-Adresse bereits in /etc/dnsmasq.conf existiert
    # - meta: end_play
    #   when: checkmyconf2.rc == 0

# Mounte das NFS-Verzeichnis /volume1/nfs-iso nach /mnt/sva
    # - name: "09 --- Mounting NFS-Share {{ nfs_server }}:{{ nfs_mount_path }}"
    #   mount:
    #     fstype: nfs
    #     opts: defaults
    #     state: mounted
    #     src: "{{ nfs_server }}:{{ nfs_mount_path }}"
    #     path: "{{ dir_nfs_root }}"
    #     backup: yes

# Wait a second
    # - name: "10 --- Wait a Second..."
    #   wait_for:
    #     timeout: 1

# Erstelle aus einem Template eine Kickstart-Datei und speichere sie auf dem NFS-Share
    # - name: "11 --- Create kickstart.cfg from kickstart.j2"
    #   template:
    #     src: "../../terraform/templates/kickstart.j2"
    #     dest: "{{ dir_nfs_root }}{{ dir_mounted_kickstart_configs }}{{ registry.hostname }}.cfg" # Hier muss noch der Pfad verifiziert werden
    #   tags:
    #     - create

# Erstelle VM-Instanz Terraform "main.tf"-file
# In dieser Datei wird auf auf das Terraform-Modul verwiesen
    - name: "12 --- Create main.tf-file from tf-vm-module.j2"
      template:
        src: "../99-jinja-templates/terraform/registry-tf.j2"
        dest: "{{ dir_terraform }}{{ registry.hostname }}/main.tf"


=======
        - "{{ dir_terraform }}{{ registry.hostname }}"
    
# Erstelle die Terraform-Files "main.tf/output.tf"-files
# main.tf
    - name: "79 --- Create main.tf-file"
      template:
        src: "../99-jinja-templates/terraform/new-vm-from-clone-with-network-settings-tf.j2"
        dest: "{{ dir_terraform }}{{ registry.hostname }}/main.tf"
    
>>>>>>> dpg-openshift
# Erzeuge und kopiere das output.tf-file in den VM-Instanz-Ordner
    - name: "80 --- Create output.tf-file"
      template:
<<<<<<< HEAD
        src: "../99-jinja-templates/terraform/output.j2"
        dest: "{{ dir_terraform }}{{ registry.hostname }}/output.tf"
      tags:
        - create

# Erstelle und kopiere das vars.tf-file in den Terraform-Module Ordner
    - name: "14 --- Create vars.tf-file from jinja-template vars.tf"
      template:
        src: "../99-jinja-templates/terraform/vars-tf.j2"
        dest: "{{ dir_terraform }}{{ registry.hostname }}/vars.tf"
      tags:
        - create

# Erstelle und kopiere das main.tf-file in den Terraform-Module Ordner
#    - name: "15a --- Create main.tf-file from jinja-template main.tf"
#      template:
#        src: "../../terraform/modules/vm-vsphere/main.tf"
#        dest: "{{ dir_terraform_module_vm }}main.tf"
#      tags:
#        - create

# Erstelle und kopiere das main.tf-file in den Terraform-Module Ordner
# Clone-Modul: Die VM wird aus einem Clone erzeugt.
    # - name: "15b --- Create main.tf-file from jinja-template main.tf"
    #   template:
    #     src: "../../terraform/templates/clone.tf.j2"
    #     dest: "{{ dir_terraform_module_vm }}main.tf"
    #   tags:
    #     - create


# Erzeuge und kopiere das output.tf-file in den Terraform-Module Ordner 
    # - name: "16 --- Create output.tf-file from jinja-template output.tf"
    #   template:
    #     src: "../../terraform/modules/vm-vsphere/output.tf"
    #     dest: "{{ dir_terraform_module_vm }}output.tf"
    #   tags:
    #     - create

=======
        src: "../99-jinja-templates/terraform/new-vm-from-clone-with-network-settings-output-tf.j2"
        dest: "{{ dir_terraform }}{{ registry.hostname }}/output.tf"
    
>>>>>>> dpg-openshift
# Erzeuge die virtuelle Maschine
    - name: "81 --- Create virtual machine with terraform"
      raw: "cd {{ dir_terraform }}{{ registry.hostname }} && /usr/local/bin/terraform init && /usr/local/bin/terraform apply -auto-approve"

# Ermittle die MAC-Adresse, der erzeugten VM
    - name: "82 --- Retrieve mac-address from created virtual machine"
      raw: "cd {{ dir_terraform }}{{ registry.hostname }} && terraform output -json | jq '.[\"mac-address\"].value' | sed -e 's|\"||g'"
      register: mac

<<<<<<< HEAD
# Erstelle für diese VM, anhand der MAC-Adresse ein PXELINUX-Config-File im TFTPROOT-Dir vom PXE-SERVER
    # - name: "19 --- Create pxelinux-config-file with mac-address-filename on tftproot on pxe-server"
    #   become: "true"
    #   become_user: "root"
    #   template:
    #     src: "../../terraform/templates/pxelinux-template.j2"
    #     dest: "{{dir_tftproot}}01-{{ mac.stdout | trim | regex_replace(':', '-')}}"
    #     mode: "0755"
    #     owner: "dnsmasq"
    #     group: "wheel"
    #   delegate_to: pxe-server

=======
>>>>>>> dpg-openshift
# Erzeuge anhand der Mac-Adresse, IP-Adresse und des Hostnames, einen DHCP-Eintrag in DNSMASQ
    - name: "83 --- Add DHCP-entry to dnsmasq.conf"
      become: "true"
      become_user: "root"
      lineinfile:
        path: /etc/dnsmasq.conf
<<<<<<< HEAD
        insertafter: "^# OpenShift-Nodes-DHCP"         
        line: "dhcp-host={{ mac.stdout | trim }},{{ registry.hostname }},{{ registry.ip }},set:ocp43"
      delegate_to: "bastion.ip"
=======
        insertafter: "^## OpenShift-Nodes-DHCP"         
        line: "dhcp-host={{ mac.stdout | trim }},{{ registry.hostname }},{{ registry.ip }},set:openshift_node"
      delegate_to: "{{bastion.ip}}"
>>>>>>> dpg-openshift
      notify: "restart dnsmasq"

# Erzeuge anhand der Mac-Adresse, IP-Adresse und des Hostnames, einen DNS-Lookup-Eintrag in DNSMASQ
    - name: "84 --- Add DNS-Lookup-entry to dnsmasq.conf"
      become: "true"
      become_user: "root"
      lineinfile:
        path: "/etc/dnsmasq.conf"
<<<<<<< HEAD
        insertafter: "^# OpenShift-Nodes-DNS" 
        line: "address=/{{ registry.hostname }}.{{domain}}/{{ registry.ip }}"
      delegate_to: "bastion.ip"
      notify: "restart dnsmasq"

# Unmounting NFS-Share
    # - name: "22 --- Unmounting NFS-Share"
    #   mount:
    #     fstype: nfs
    #     opts: defaults
    #     state: absent
    #     src: "{{ nfs_server }}{{ nfs_mount_path }}"
    #     path: "{{ dir_nfs_root }}"
    #     backup: yes

=======
        insertafter: "^## OpenShift-Nodes-DNS" 
        line: "address=/{{ registry.hostname }}.{{clustername}}.{{domain}}/{{ registry.ip }}"
      delegate_to: "{{bastion.ip}}"
      notify: "restart dnsmasq"

>>>>>>> dpg-openshift
# Starte den DNS-Dienst erneut, wenn sich etwas an der DNS-Konfiguration geändert hat.
  handlers:
    - name: "restart dnsmasq"
      become: "true"
      become_user: "root"
      service:
        name: dnsmasq
        state: restarted
<<<<<<< HEAD
      delegate_to: "bastion.ip"

=======
      delegate_to: "{{bastion.ip}}"
>>>>>>> dpg-openshift
