---
- name: "{{ lookup('pipe','date \"+%Y-%m-%d %H-%M-%S\"') }} | Playbook - Configure the Registry-VM"
  hosts: "{{ registry.ip }}"
  become: "true"
  gather_facts: "false"
  vars_files:
    - "../vars/vars.yaml"
  tasks:
# Zeitausgabe
    - name: "--- Starte Playbook: {{ lookup('pipe','date \"+%Y-%m-%d %H-%M-%S\"') }}"
      debug: msg="{{ lookup('pipe','date \"+%Y-%m-%d %H-%M-%S\"') }}"

# Do ssh-copy-id to localhost, so that ansible can communicate with localhost
    - name: "85 - ssh-copy-id as user-root to {{registry.ip}}"
      become: "true"
      become_user: "root"
      raw: "sshpass -f '/root/rootpassword' ssh-copy-id -i /root/.ssh/id_rsa -o StrictHostKeyChecking=no root@{{registry.ip}}"
      delegate_to: "localhost"

# Install some software
    - name: "86a - Install Epel-Release"
      yum:
        name: 
          - "epel-release"
        state: "present"
      
    - name: "86b - Install podman"
      yum:
        name: 
          - "podman"
          - "wget"
          #- "openssl11"
          - "openssl"
          - "httpd-tools"
        state: "present"

# Create Working-Directories on Install-VM
    - name: "87 --- Create Working-Directories on {{ install_vm.hostname }}"
      file:
        path: "{{ item }}"
        state: "directory"
        recurse: "true"
      with_items:
        - "{{ dir_downloads }}"
      delegate_to: "localhost"

# Create Working-Directories on {{ registry.ip }}
    - name: "88 --- Create Working-Directories on {{ registry.ip }}"
      file:
        path: "{{ item }}"
        state: "directory"
        recurse: "true"
      with_items:
        - "{{dir_registry_auth}}"
        - "{{dir_registry_certs}}"
        - "{{dir_registry_data}}"

# Download openshift software from internet
# Download oc-client
    - name: "89 - Download OpenShift - oc-client on {{ install_vm.hostname }}"
      get_url:
        url="{{link_to_oc}}"
        dest="{{ dir_downloads }}{{file_oc}}"
      register: get_oc
      tags:
        - downloads
      delegate_to: "localhost"

# Download openshift-installer
    # - name: "90 - Download OpenShift - openshift-installer on {{ install_vm.hostname }}"
    #   get_url:
    #     url="{{link_to_openshift_installer}}"
    #     dest="{{ dir_downloads }}{{file_openshift_installer}}"
    #   register: get_installer
    #   tags:
    #     - downloads
    #   delegate_to: "localhost"


# Download Kernel
    # - name: "91 - Download CoreOS - Kernel on {{ install_vm.hostname }}"
    #   get_url:
    #     url="{{link_to_coreos_kernel}}"
    #     dest="{{ dir_downloads }}{{file_coreos_kernel}}"
    #   register: get_kernel
    #   tags:
    #     - downloads
    #   delegate_to: "localhost"

    # - debug: 
    #     msg="{{file_coreos_kernel}} was downloaded"
    #   when: get_kernel|changed
    #   tags:
    #     - downloads
    #   delegate_to: "localhost"

# Download Initrd
    # - name: "92 - Download CoreOS - Initrd on {{ install_vm.hostname }}"
    #   get_url:
    #     url="{{link_to_coreos_initrd}}"
    #     dest="{{ dir_downloads }}{{file_coreos_initrd}}"
    #   register: get_initrd
    #   tags:
    #     - downloads
    #   delegate_to: "localhost"

    # - debug: 
    #     msg="{{file_coreos_kernel}} was downloaded"
    #   when: get_initrd|changed
    #   tags:
    #     - downloads
    #   delegate_to: "localhost"

# Download RAW_GZ
    # - name: "93 - Download CoreOS - raw_gz on {{ install_vm.hostname }}"
    #   get_url:
    #     url="{{link_to_coreos_raw_gz}}"
    #     dest="{{ dir_downloads }}{{file_coreos_raw_gz}}"
    #   register: get_rawgz
    #   tags:
    #     - downloads
    #   delegate_to: "localhost"

    # - debug: 
    #     msg="{{file_coreos_kernel}} was downloaded"
    #   when: get_rawgz|changed
    #   tags:
    #     - downloads
    #   delegate_to: "localhost"

    # - name: "10 - Download OpenShift-Software"
    #   get_url:
    #     url: "{{ item }}"
    #     dest: "{{ dir_downloads }}"
    #   with_items:
    #     - "{{ link_to_oc }}"
    #     - "{{ link_to_openshift_installer }}"
    #     - "{{ link_to_coreos_kernel }}"
    #     - "{{ link_to_coreos_initrd }}"
    #     - "{{ link_to_coreos_raw_gz }}"
    #   delegate_to: "localhost"

# Extraction of zip-archive
    - name: "94 - Extract the oc-client on {{ install_vm.hostname }}"
      unarchive:
        src: "{{ dir_downloads }}openshift-client-linux-{{version_openshift}}.tar.gz"
        dest: "{{ dir_downloads }}"
        remote_src: "true"
      delegate_to: "localhost"

# Extraction of zip-archive
    # - name: "95 - Extract the openshift-installer on {{ install_vm.hostname }}"
    #   unarchive:
    #     src: "{{ dir_downloads }}openshift-install-linux-{{version_openshift}}.tar.gz"
    #     dest: "{{ dir_downloads }}"
    #     remote_src: "true"
    #   delegate_to: "localhost"

# Make oc executable >> copy to /usr/local/bin/oc
    - name: "96 - copy oc to /usr/local/bin and make executable"
      copy:
        src: "{{ dir_downloads }}oc"
        dest: "/usr/local/bin/oc"
        mode: "0755"

# Make openshift-installer executable >> copy to /usr/local/bin/openshift-install
    # - name: "97 - copy openshift-install to /usr/local/bin and make executable"
    #   copy:
    #     src: "{{ dir_downloads }}openshift-install"
    #     dest: "/usr/local/bin/openshift-install"
    #     mode: "0755"

# Create SSL-Cert for Registry
    - name: "98 - Create SSL-Cert for Registry"
      #raw: "cd {{dir_registry_certs}} && openssl11 req -newkey rsa:4096 -nodes -sha256 -keyout domain.key -x509 -days 365 -out domain.crt -subj '/C=DE/ST=Brandenburg/L=Cottbus/O=Home/OU=local/CN={{registry.hostname}}.{{clustername}}.{{domain}}' -addext 'subjectAltName = DNS:{{registry.hostname}}.{{clustername}}.{{domain}}'"
      raw: "cd {{dir_registry_certs}} && openssl req -newkey rsa:4096 -nodes -sha256 -keyout domain.key -x509 -days 365 -out domain.crt -subj '/C=DE/ST=Brandenburg/L=Cottbus/O=Home/OU=local/CN={{registry.hostname}}.{{clustername}}.{{domain}}' -addext 'subjectAltName = DNS:{{registry.hostname}}.{{clustername}}.{{domain}}'"
      tags:
        - "SSLa"

# Create User for registry
    - name: "99 - Create User {{registry_user}} for Registry"
      raw: "htpasswd -bBc {{dir_registry_auth}}htpasswd {{registry_user}} {{registry_pass}}"


# Run the mirror-registry with Podman
    - name: "100 - Start Registry with podman as mirror-registry"
      command: "podman run --name mirror-registry -p {{registry_port}}:{{registry_port}} \ 
     -v {{dir_registry_data}}:/var/lib/registry:z \
     -v {{dir_registry_auth}}:/auth:z \
     -e 'REGISTRY_AUTH=htpasswd' \
     -e 'REGISTRY_AUTH_HTPASSWD_REALM=Registry Realm' \
     -e REGISTRY_AUTH_HTPASSWD_PATH=/auth/htpasswd \
     -v {{dir_registry_certs}}:/certs:z \
     -e REGISTRY_HTTP_TLS_CERTIFICATE=/certs/domain.crt \
     -e REGISTRY_HTTP_TLS_KEY=/certs/domain.key \
     -e REGISTRY_COMPATIBILITY_SCHEMA1_ENABLED=true \
     -d docker.io/library/registry:2"

# Copy certs to trust-store
    - name: "101 - Copy registry-certificate to linux-trust-store"
      copy:
        src: "{{dir_registry_certs}}domain.crt"
        dest: "/etc/pki/ca-trust/source/anchors/domain.crt"
        remote_src: "true"

# Update the Trust-Store
    - name: "102 - Update Linux Trust-Store"
      raw: "update-ca-trust" 

# Copy the registry-cert from registry-vm to install-vm
    - name: "103 - Copy registry-certificate to local Linux Trust-Store"
      raw: "scp {{registry.ip}}:{{dir_registry_certs}}domain.crt /etc/pki/ca-trust/source/anchors/domain.crt" 
      delegate_to: "localhost"

# Update the Trust-Store of install-vm
    - name: "104 - Update local Linux Trust-Store"
      raw: "update-ca-trust" 
      delegate_to: "localhost"

# Configure the firewall
    # - name: "21 - Configure firewalld to open port 5000 for mirror-registry"
    #   firewalld:
    #     permanent: "true"
    #     state: "enabled"
    #     port: "5000/tcp"
    #   notify:
    #     - restart firewalld

# Disable Firewalld
    - name: "105 - Disable Firewalld"
      systemd:
        name: "firewalld"
        state: "stopped"
        enabled: "no"

# Restart the registry-pod
    - name: "106 - Restart the registry-pod"
      raw: "podman stop mirror-registry && podman start mirror-registry" 

    - name: "107 - Summary"
      debug: msg="Login with = podman login {{registry.hostname}}.{{clustername}}.{{domain}}:{{registry_port}} -u {{registry_user}}"


# Zeitausgabe
    - name: "--- Ende Playbook: {{ lookup('pipe','date \"+%Y-%m-%d %H-%M-%S\"') }}"
      debug: msg="{{ lookup('pipe','date \"+%Y-%m-%d %H-%M-%S\"') }}"


  handlers:
    - name: "restart firewalld"
      systemd:
        name: "firewalld"
        state: "restarted"
...