# OpenShift
clustername: "ocp-patrick"


# Terraform
tf_version: "0.13.5"
tf_zip_filename: "terraform_{{tf_version}}_linux_amd64.zip"

## Terraform - vSphere-Plugin
tf_vsphere_plugin_version: "1.24.2"
tf_vsphere_plugin_zip_filename: "terraform-provider-vsphere_{{tf_vsphere_plugin_version}}_linux_amd64.zip"

# Download-Links
download_tf: "https://releases.hashicorp.com/terraform/{{tf_version}}/terraform_{{tf_version}}_linux_amd64.zip"
download_tf_vsphere_plugin: "https://releases.hashicorp.com/terraform-provider-vsphere/{{tf_vsphere_plugin_version}}/terraform-provider-vsphere_{{tf_vsphere_plugin_version}}_linux_amd64.zip"

# Working directories >> always end with Slash /
dir_root: "/opt/patrick/"
dir_cluster: "{{dir_root}}{{clustername}}/"
dir_terraform: "{{dir_root}}terraform/"
dir_terraform_vsphere_plugin: "{{dir_terraform}}vsphere_plugin"
dir_tools: "{{dir_root}}tools/"

# Netzwerk / IPs / Hostnames
masters:
  - name: "master01"
    hostname: "ocp-master-01"
    ip: "10.0.249.111"
  - name: "master02"
    hostname: "ocp-master-02"
    ip: "10.0.249.112"
  - name: "master03"
    hostname: "ocp-master-03"
    ip: "10.0.249.113"

workers:
  - name: "worker01"
    hostname: "ocp-worker-01"
    ip: "10.0.249.114"
  - name: "worker02"
    hostname: "ocp-worker-02"
    ip: "10.0.249.115"
  - name: "worker03"
    hostname: "ocp-worker-03"
    ip: "10.0.249.116"

bstrp:
  name: "bootstrap"
  hostname: "ocp-bootstrap"
  ip: "10.0.249.117"

bastion:
  name: "bastion"
  hostname: "ocp-bastion"
  ip: "10.0.249.117"

registry:
  name: "registry"
  hostname: "ocp-registry"
  ip: "10.0.249.118"

lb:
  name: "load-balancer"
  hostname: "ocp-lb-01"
  app:
    ip: "10.0.249.119"
  api:
    ip: "10.0.249.119"
  api_int:
    ip: "10.0.249.119"

# DNSMASQ-Settings
dhcp_range: "10.0.249.40,10.0.249.250,255.255.255.0,12h"
dhcp_subnetmask: "255.255.255.0"
dhcp_gateway: "10.0.249.1"
ntpserver: "10.0.249.1"
interface: "ens192"
listen_address: "{{ bastion.ip }}"
boot_script: "pxelinux.0"

# HAPROXY-Settings
openshift_api_server:
  frontend:
    ip: "*"
    port: "6443"
  backend:
    servers: "{{ masters + [ bstrp ] }}"

machine_config_server:
  frontend:
    ip: "*"
    port: "22623"
  backend:
    servers: "{{ masters + [ bstrp ] }}"

ingress_http:
  frontend:
    ip: "*"
    port: "80"
  backend:
    servers: "{{ workers }}"

ingress_https:
  frontend:
    ip: "*"
    port: "443"
  backend:
    servers: "{{ workers }}"

image_registry:
  frontend:
    ip: "*"
    port: "5000"
  backend:
    servers: "{{ workers }}"

hostname: "default"
domain: "home.local"
dns_server_ip: "10.0.249.53"

dir_tftproot: "/tftproot/pxelinux.cfg/"
vm_type: "worker"
ip: "10.0.249.111"
cpu: "1"
ram: "1024"
disksize: "120"
boot_delay: "20000"
dir_root: "/opt/sva/"
dir_terraform: "{{dir_root}}terraform/"
dir_terraform_modules: "{{dir_terraform}}modules/"
dir_terraform_module_vm: "{{dir_terraform_modules}}vm-vsphere/"
dir_vmware: "/dc-home/vm/spielwiese"
dir_nfs_root: "/mnt/sva/"
dir_mounted_kickstart_configs: "kickstart-configs/"
vsphere_server: "vcenter.home.local"
vsphere_user: "administrator@home.local"
vsphere_pass: "Test1234!"
nfs_server: "nas.home.local"
nfs_server_name: "nas.home.local"
nfs_path: "/volume1/nfs-iso/downloaded-iso/linux/"
nfs_mount_path: "/volume1/nfs-iso/"
nfs_software_folder: "/volume1/nfs-iso/downloaded-iso/linux/"
nfs_kickstart_folder: "/volume1/nfs-iso/kickstart-configs/"
iso_centos77: "CentOS-7-x86_64-DVD-1908.iso"
nfs_path_os_rhel77: "CentOS-7-x86_64-DVD-1908.iso"
pxe_vmlinux_kernel: "kernels_initrd/centos77/vmlinuz"
pxe_initrd_image: "kernels_initrd/centos77/initrd.img"
ntp_server: "router.home.local"
kickstart_file: "{{hostname}}.cfg"