# OpenShift
clustername: "openshift"
domain: "local"
dns_server_ip: "11.11.11.53"
version_openshift: "4.5.23"
version_core_os: "4.5.6"
version_major: "4.5"
clusternetwork: "10.254.0.0/16"
servicenetwork: "10.255.0.0/16"

ignition_filename_master: "master.ign"
ignition_filename_worker: "worker.ign"
ignition_filename_bootstrap: "bootstrap.ign"

# VMware-Settings
vsphere_server: "vcenter.home.local"
vsphere_user: "administrator@home.local"
vsphere_pass: "Test1234!"
vsphere_cluster: "cluster-home"
vsphere_datacenter: "dc-home"
vsphere_rp: "rp-home"
vsphere_datastore: "openshift_storage"
vsphere_network: "dpg-openshift"
vsphere_folder: "dc-home/vm/openshift"
vsphere_master_cpu: "8"
vsphere_master_ram: "16384"
vsphere_master_disksize: "120"
vsphere_worker_cpu: "4"
vsphere_worker_ram: "8192"
vsphere_worker_disksize: "120"
vsphere_bstrp_cpu: "8"
vsphere_bstrp_ram: "16384"
vsphere_bstrp_disksize: "120"


dir_vmware: "/dc-home/vm/openshift"
#cpu: "1"
#ram: "1024"
disksize: "120"
boot_delay: "30000"
vm_type: "worker"

# Clients / Software
link_to_oc: "https://mirror.openshift.com/pub/openshift-v4/clients/ocp/{{version_openshift}}/openshift-client-linux-{{version_openshift}}.tar.gz"
link_to_openshift_installer: "https://mirror.openshift.com/pub/openshift-v4/clients/ocp/{{version_openshift}}/openshift-install-linux-{{version_openshift}}.tar.gz"
link_to_coreos_kernel: "https://mirror.openshift.com/pub/openshift-v4/x86_64/dependencies/rhcos/{{version_major}}/{{version_core_os}}/rhcos-{{version_core_os}}-x86_64-installer-kernel-x86_64"
link_to_coreos_initrd: "https://mirror.openshift.com/pub/openshift-v4/x86_64/dependencies/rhcos/{{version_major}}/{{version_core_os}}/rhcos-{{version_core_os}}-x86_64-installer-initramfs.x86_64.img"
link_to_coreos_raw_gz: "https://mirror.openshift.com/pub/openshift-v4/x86_64/dependencies/rhcos/{{version_major}}/{{version_core_os}}/rhcos-{{version_core_os}}-x86_64-metal.x86_64.raw.gz"
file_coreos_kernel: "rhcos-{{version_core_os}}-x86_64-installer-kernel-x86_64"
file_coreos_initrd: "rhcos-{{version_core_os}}-x86_64-installer-initramfs.x86_64.img"
file_coreos_raw_gz: "rhcos-{{version_core_os}}-x86_64-metal.x86_64.raw.gz"
file_oc: "openshift-client-linux-{{version_openshift}}.tar.gz"
file_openshift_installer: "openshift-install-linux-{{version_openshift}}.tar.gz"
dir_mnt_to_core_os: "{{dir_mnt}}downloaded-iso/linux/"

# Red Hat / Password-Files
pull_secret: "/root/pull-secret.json"
rootpw: "/root/rootpassword"
pull_secret_file_name: "pull-secret"

# Mirror-Registry
registry_user: "reguser" # No underscore allowed!
registry_pass: "Test1234"
registry_port: "5000"
local_registry: "{{registry.hostname}}.{{domain}}:{{registry_port}}"
product_repo: "openshift-release-dev"
local_repository: "ocp4/openshift4"
release_name: "ocp-release"
ocp_release: "{{version_openshift}}-x86_64"
pull_secret_for_mirror: "/root/pull-secret.json"

# Terraform
tf_version: "0.14.2"
tf_zip_filename: "terraform_{{tf_version}}_linux_amd64.zip"

## Terraform - vSphere-Plugin
tf_vsphere_plugin_version: "1.24.2"
tf_vsphere_plugin_zip_filename: "terraform-provider-vsphere_{{tf_vsphere_plugin_version}}_linux_amd64.zip"
tf_jinja_template: "ocp-master-worker-nodes.tf.j2"

# Download-Links
download_tf: "https://releases.hashicorp.com/terraform/{{tf_version}}/terraform_{{tf_version}}_linux_amd64.zip"
download_tf_vsphere_plugin: "https://releases.hashicorp.com/terraform-provider-vsphere/{{tf_vsphere_plugin_version}}/terraform-provider-vsphere_{{tf_vsphere_plugin_version}}_linux_amd64.zip"

# Working directories >> always end with Slash /
#dir_root: "/opt/patrick/"
dir_cluster: "{{dir_root}}{{clustername}}/"
dir_install_config: "{{dir_cluster}}install-config/"
dir_terraform: "{{dir_root}}terraform/"
dir_terraform_modules: "{{dir_terraform}}modules/"
dir_terraform_module_vm: "{{dir_terraform_modules}}vm-vsphere/"
dir_terraform_vsphere_plugin: "{{dir_terraform}}vsphere_plugin"
dir_tools: "{{dir_root}}tools/"
dir_root: "/opt/sva/"
dir_downloads: "{{dir_tools}}downloads/"
dir_downloaded_images: "{{dir_root}}downloads/"
dir_nfs_root: "/mnt/sva/"
dir_mounted_kickstart_configs: "kickstart-configs/"
dir_tftproot: "/tftproot/pxelinux.cfg/"
dir_tftp_root: "/tftproot/"
dir_http_server: "/var/www/html/{{clustername}}/"
dir_pi_home: "/home/pi/"
dir_registry_auth: "{{dir_root}}registry/auth/"
dir_registry_certs: "{{dir_root}}registry/certs/"
dir_registry_data: "{{dir_root}}registry/data/"
dir_mnt: "/mnt/{{clustername}}/"
dir_coreos_files: "kernel_initrd/"
dir_backup: "{{dir_root}}backup/"
dir_backup_manifest_files: "{{dir_backup}}manifest_files/"
dir_backup_ignition_files: "{{dir_backup}}ignition_files/"
dir_backup_ssh_keys: "{{dir_backup}}ssh_keys/"
dir_backup_tftp: "{{dir_backup}}tftp/"
dir_backup_install_config: "{{dir_backup}}install_config/"
dir_backup_dnsmasq: "{{dir_backup}}dnsmasq/"
dir_key_to_nodes: "/root/.ssh/"
key_to_nodes_name: "id_{{clustername}}"

# Netzwerk / IPs / Hostnames
# OpenShift-Master-Nodes
masters:
  - name: "master01"
    hostname: "ocp-master-01"
    ip: "11.11.11.111"
    cpu: "8"
    ram: "16384"
    disk: "200"
    mac: "11:22:33:44:55:61"
    datastore: "openshift_storage"
  - name: "master02"
    hostname: "ocp-master-02"
    ip: "11.11.11.112"
    cpu: "8"
    ram: "16384"
    disk: "200"
    mac: "11:22:33:44:55:62"
    datastore: "openshift_storage"
  - name: "master03"
    hostname: "ocp-master-03"
    ip: "11.11.11.113"
    cpu: "8"
    ram: "16384"
    disk: "200"
    mac: "11:22:33:44:55:63"
    datastore: "openshift_storage"

# OpenShift-Worker-Nodes
workers:
  - name: "worker01"
    hostname: "ocp-worker-01"
    ip: "11.11.11.114"
    cpu: "8"
    ram: "16384"
    disk: "200"
    mac: "11:22:33:44:55:64"
    datastore: "openshift_storage"
  - name: "worker02"
    hostname: "ocp-worker-02"
    ip: "11.11.11.115"
    cpu: "8"
    ram: "16384"
    disk: "200"
    mac: "11:22:33:44:55:65"
    datastore: "openshift_storage"
  - name: "worker03"
    hostname: "ocp-worker-03"
    ip: "11.11.11.116"
    cpu: "8"
    ram: "16384"
    disk: "200"
    mac: "11:22:33:44:55:66"
    datastore: "openshift_storage"

# Temporary Bootstrap-VM
bstrp:
  name: "bootstrap"
  hostname: "ocp-bootstrap"
  ip: "11.11.11.117"
  cpu: "8"
  ram: "16384"
  disk: "200"
  mac: "11:22:33:44:55:60"
  datastore: "openshift_storage"

# Install-VM
install_vm:
  name: "Install-VM"
  hostname: "install-vm"

# Bastion-Host
bastion:
  name: "bastion"
  hostname: "ocp-bastion"
  ip: "11.11.11.53"
  cpu: "2"
  ram: "4096"
  disk: "200"
  mac: "00:50:56:a6:83:ae"

# Image-Registry
registry:
  name: "registry"
  hostname: "ocp-registry"
  ip: "11.11.11.118"
  cpu: "2"
  ram: "2048"
  disk: "200"
  mac: "00:50:56:a6:bf:52"

# Raspi
pi:
  hostname: "pi"
  ip: "10.0.249.53"

# PXE-Server
pxe:
  hostname: "pxe-server"
  ip: "10.0.249.60"

# Load-Balancer
lb:
  name: "load-balancer"
  hostname: "ocp-lb01"
  ip: "11.11.11.119"
  cpu: "1"
  ram: "1024"
  disk: "200"
  mac: "00:50:56:a6:cb:f9"
  app:
    ip: "11.11.11.119"
  api:
    ip: "11.11.11.119"
  api_int:
    ip: "11.11.11.119"

# DNSMASQ-Settings
dhcp_range: "11.11.11.40,11.11.11.250,255.255.255.0,12h"
dhcp_subnetmask: "255.255.255.0"
dhcp_gateway: "11.11.11.1"
ntpserver: "11.11.11.1"
interface: "ens192"
listen_address: "{{ bastion.ip }}"
boot_script: "pxelinux.0"

# HAPROXY-Settings
openshift_api_server:
  frontend:
    ip: "*"
    port: "6443"
  backend:
    servers: "{{ masters + [ bstrp ] }}"

machine_config_server:
  frontend:
    ip: "*"
    port: "22623"
  backend:
    servers: "{{ masters + [ bstrp ] }}"

ingress_http:
  frontend:
    ip: "*"
    port: "80"
  backend:
    servers: "{{ workers }}"

ingress_https:
  frontend:
    ip: "*"
    port: "443"
  backend:
    servers: "{{ workers }}"

image_registry:
  frontend:
    ip: "*"
    port: "5000"
  backend:
    servers: "{{ workers }}"

#hostname: "default"




# NFS-Settings
nfs_server: "nas.home.local"
nfs_server_ip: "11.11.11.150"
nfs_server_name: "nas.home.local"
nfs_path: "/volume1/nfs-iso/downloaded-iso/linux/"
nfs_mount_path: "/volume1/nfs-iso/"
nfs_software_folder: "/volume1/nfs-iso/downloaded-iso/linux/"
nfs_kickstart_folder: "/volume1/nfs-iso/kickstart-configs/"
nfs_path_os_rhel77: "CentOS-7-x86_64-DVD-1908.iso"
iso_centos77: "CentOS-7-x86_64-DVD-1908.iso"

# PXE-Settings
pxe_vmlinux_kernel: "kernels_initrd/centos77/vmlinuz"
pxe_initrd_image: "kernels_initrd/centos77/initrd.img"
ntp_server: "router.home.local"

#kickstart_file: "{{hostname}}.cfg"

image_block: |
  imageContentSources:
  - mirrors:
    - {{ registry.hostname }}.{{ clustername }}.{{ domain }}:{{ registry_port }}/ocp4/openshift4
    source: quay.io/openshift-release-dev/ocp-release
  - mirrors:
    - {{ registry.hostname }}.{{ clustername }}.{{ domain }}:{{ registry_port }}/ocp4/openshift4
    source: quay.io/openshift-release-dev/ocp-v4.0-art-dev