---
- name: "Configuration of a load-balancer"
  hosts: "localhost"
  gather_facts: "false"
  tasks:
    - name: "01 - Render terraform-template for load-balancer-vm"
      template:
        src: ""
        dest: ""
...