- name: "Install-VM"
  hosts: 127.0.0.1
  gather_facts: "false"
  vars_files:
    - "../vars/vars.yaml"
  tasks:
    - name: "01 --- Retrieve mac-address from created virtual machine"
      raw: "cd {{ dir_terraform }}{{ lb.hostname }} && terraform output -json | jq '.[\"mac-address\"].value' | sed -e 's|\"||g'"
      register: mac

    - name: "01 --- Delete pxelinux-config-file on pxe-server"
      become: "true"
      become_user: "root"
      raw: "rm -f {{dir_tftproot}}01-{{ mac.stdout | trim | regex_replace(':', '-')}}"
      delegate_to: pxe-server

    - name: "02 --- Remove entry from dnsmasq.conf"
      become: "true"
      become_user: "root"
      lineinfile:
        path: "/etc/dnsmasq.conf"
        line: "dhcp-host={{ mac.stdout | trim }},{{ lb.hostname }},{{ ip }},set:ocp43"
        state: "absent"
      delegate_to: pi
      notify: 
        - "restart dnsmasq"


    - name: "03 --- Remove entry from dnsmasq.conf"
      become: "true"
      become_user: "root"
      lineinfile:
        path: "/etc/dnsmasq.conf"
        line: "address=/{{ lb.hostname }}.ocp43-patrick.home.local/{{ ip }}"
        state: "absent"
      delegate_to: pi
      notify: 
        - "restart dnsmasq"
    
    - name: "04 --- Delete virtual machine with terraform"
      raw: "cd {{ dir_terraform }}{{ lb.hostname }} && terraform init && terraform destroy -auto-approve"
#    - name: "05 --- Delete folder {{ dir_terraform }}{{ lb.hostname }}"
#      raw: "rm -rf {{ dir_terraform }}{{ lb.hostname }}"

  handlers:
    - name: "restart dnsmasq"
      become: "true"
      become_user: "root"
      service:
        name: dnsmasq
        state: restarted
      delegate_to: pi
