---
# In dem Default-Namespace benötigen wir ein Image-Pull-Secret mit den Credentials zur Registry in Artifactory
- name: "### --- 10 - Create pull-secret"
  shell: |
    /usr/local/bin/oc create secret generic artifactory-image-pull-secret \
     --from-file=.dockerconfigjson="{{ pull_secret_fullpath }}" \
     --type=kubernetes.io/dockerconfigjson \
     -n default \
     --config="{{ kubeconfig }}" 
  delegate_to: "{{bastion.ip}}"

# Verlinke den ServiceAccount nfs-client-provisioner mit dem image-pull-secret  
- name: "### --- 11 - Link pull-secret with service account nfs-client-provisioner"
  shell: |
    /usr/local/bin/oc secrets link nfs-client-provisioner artifactory-image-pull-secret \
     --for=pull \
     -n default \
     --config="{{ kubeconfig }}" 
  delegate_to: "{{bastion.ip}}"
