---
# Dieses Playbook erzeugt das Deployment in OpenShift und führt dieses aus
# Das YAML-File wird automatisch mit Variablen gefüllt und an die Stelle im Bastion kopiert
- name: "### --- 14 - Render nfs_provisioner_deployment.yaml from a template"
  template: 
    src: "../99-jinja-templates/nfs-provisioner/storage_deployment.yaml.j2"
    dest: "{{ dir_post_install_config }}nfs_provisioner_deployment.yaml"
    owner: root
    group: root
    mode: '0644'
    force: yes

# Führe folgendes "oc create"-Kommando aus um das Deployment zu starten
- name: "### --- 15 - Deploy nfs_provisioner_deployment.yaml for nfs-client-provisioner"
  shell: |
    /usr/local/bin/oc create -f "{{ dir_post_install_config }}nfs_provisioner_deployment.yaml" \
      --config="{{ kubeconfig }}" 
  delegate_to: "{{bastion.ip}}"

    