---
# Dieses Playbook erstellt die Arbeitsverzeichnisse auf dem Bastion-Host
- name: "01 - Create SSH-Connection to {{bastion.ip}}"
  command: "sshpass -f '/root/rootpassword' ssh-copy-id -i /root/.ssh/id_rsa -o StrictHostKeyChecking=no {{bastion.ip}}"
  delegate_to: "localhost"

- name: "02 - Copy password-file  to /root/"
  copy:
    src: "{{rootpw}}"
    dest: "{{rootpw}}"

- name: "03 - Update yum-repos EPEL-RELEASE"
  become: "true"
  yum:
    name:
      - "epel-release"
    state: "present"

- name: "04 - Update yum-repos centos-release-ansible-29.noarch"
  become: "true"
  yum:
    name:
      - "centos-release-ansible-29.noarch"
    state: "present"

- name: "05 - Install necassary software programs"
  become: "true"
  yum:
    name:
      - ansible.noarch
      - git
      - sshpass
      - wget.x86_64
      - jq.x86_64
      - podman.x86_64
      - skopeo.x86_64
      - nfs-utils.x86_64
      - unzip
      - dnsmasq
      - policycoreutils-python
      - syslinux
      - httpd
      - unzip
    state: "present"
  tags:
    - installed

- name: "06 - Create User DNSMASQ in Group wheel"
  user:
    name: "dnsmasq"
    groups: "wheel"
    state: "present"
  tags:
    - userdnsmasq

- name: "06 - Create SSH-Keypair"
  raw: "ssh-keygen -q -t rsa -N '' -f /root/.ssh/{{key_to_nodes_name}} <<<y 2>&1 >/dev/null"

- name: "07 - Create SSH-Connection on {{bastion.hostname}} itself"
  command: "sshpass -f '{{rootpw}}' ssh-copy-id -i /root/.ssh/{{key_to_nodes_name}} -o StrictHostKeyChecking=no localhost"

- name: "08 - Create working directories" 
  file:
    path: "{{ item }}"
    owner: root
    group: root
    mode: '0755'
    state: directory
    recurse: true
  with_items:
    - "{{ dir_root }}"
    - "{{ dir_tools }}"
    - "{{ dir_cluster }}"
    - "{{ dir_install_config }}"
    - "{{ dir_http_server }}"
    - "{{ dir_mnt }}"
    - "{{ dir_terraform }}"
    - "{{ dir_backup }}"
    - "{{ dir_backup_manifest_files }}"
    - "{{ dir_backup_ignition_files }}"
    - "{{ dir_backup_ssh_keys }}"
    - "{{ dir_backup_tftp }}"
    - "{{ dir_backup_install_config }}"
    - "{{ dir_backup_dnsmasq }}"
  tags:
    - rerun

- name: "08a - Create working directories for tftproot" 
  file:
    path: "{{ item }}"
    owner: "dnsmasq"
    group: "wheel"
    mode: '0755'
    state: directory
    recurse: true
  with_items:
    - "{{ dir_tftp_root }}"
    - "{{ dir_tftp_root }}{{ dir_coreos_files }}"
    - "{{ dir_tftp_root }}pxelinux.cfg"
  tags:
    - rerun

- name: "08b - Copy syslinux-file to {{dir_tftp_root}}"
  copy:
    owner: "dnsmasq"
    group: "wheel"
    src: "/usr/share/syslinux/{{ item }}"
    dest: "{{ dir_tftp_root }}{{ item }}"
    remote_src: "true"
  with_items:
    - "pxelinux.0"
    - "menu.c32"
  tags:
    - rerun

# 21.09.2020 - New Feature to backup the SSH-Key-Folder-Content
- name: "09 - Backup SSH-Keys to /opt/sva/backup"
  command: cp "{{ dir_key_to_nodes }}{{ item }}" "{{ dir_backup_ssh_keys }}"
  with_items:
    - "{{ key_to_nodes_name }}"
    - "{{ key_to_nodes_name }}.pub"
  tags:
    - rerun

- name: "10 - Copy CoreOS-Images to tftproot"
  copy:
    owner: "dnsmasq"
    group: "wheel"
    src: "{{item}}"
    dest: "{{ dir_tftp_root }}{{ dir_coreos_files }}"  
  loop:
    - "{{ dir_downloaded_images }}{{file_coreos_kernel}}"
    - "{{ dir_downloaded_images }}{{file_coreos_initrd}}"
    #- "{{ dir_downloaded_images }}{{file_coreos_raw_gz}}"
  tags:
    - rerun

- name: "11 - Copy CoreOS-Raw-GZ to {{dir_http_server}}"
  copy:
    src: "{{item}}"
    dest: "{{ dir_http_server }}"  
  loop:
    #- "{{ dir_downloaded_images }}{{file_coreos_kernel}}"
    #- "{{ dir_downloaded_images }}{{file_coreos_initrd}}"
    - "{{ dir_downloaded_images }}{{file_coreos_raw_gz}}"
  tags:
    - rerun


- name: "12 - Open some firewall-ports"
  firewalld:
    service: "{{item}}"
    permanent: yes
    state: "enabled"
  with_items:
    - "tftp"
    - "http"
    - "https"
    - "dns"
    - "dhcp"
  tags:
    - rerun
