---
# Dieses Playbook mounted das Software-Verzeichnis an den Bastion-Host an die unter path angegebene Stelle.
# In dem gemounteten Pfad liegen die wichtigen Installationsdateien für CoreOS und OpenShift.
- name: "13 - Mounting NFS-Share"
  mount:
    fstype: nfs
    opts: "nfsvers=3,nolock"
    dump: 0
    passno: 0
    state: mounted
    src: "{{nfs_server}}:{{ nfs_mount_path }}"
    path: "{{ dir_mnt }}"
  tags:
    - rerun

- name: "14 - Wait a Second..."
  wait_for:
    timeout: 1
  tags:
    - rerun

   
# - name: "Unmounting NFS-Share"
  # mount:
  #   fstype: nfs
  #   opts: "nfsvers=3,nolock"
  #   dump: 0
  #   passno: 0
  #   state: absent
  #   src: "{{ src_nas_mount }}"
  #   path: "{{ dir_mnt }}"