---
# Dieses Playbook erzeugt Symlinks von den per NFS gemounteten Dateien und zeigt an die entsprechenden Stellen im TFTP-Server und HTTP-Server
- name: "15 - Create links to CoreOS files in tftp server"
  file:
    src: "{{ dir_mnt_to_core_os }}{{ item }}"
    dest: "{{ dir_tftp_root }}{{ dir_coreos_files }}{{ item }}"
    owner: root
    group: root
    # mode: '0755'
    state: link
  with_items:
    - "{{ file_coreos_initrd }}"
    - "{{ file_coreos_kernel }}"


- name: "16 - Create links to CoreOS files in http server"
  file:
    src: "{{ dir_mnt_to_core_os }}{{ file_coreos_raw_gz }}"
    dest: "{{ dir_http_server }}{{ file_coreos_raw_gz }}"
    owner: root
    group: root
    # mode: '0755'
    state: link
