---
# Dieses Playbook bereitet die CLI-Tools zum Einsatz bzw. zur Verwendung vor.
# 22.09.2020 - Anpassung: Die TAR-File werden vom Software-Verzeichnis kopiert. Nicht mehr die Tools oc, kubectl und openshift-install einzeln
- name: "57 - Copy OC-Client-TAR-File and Openshift-install-TAR-File to bastion"
  copy:
    src: "{{ dir_downloaded_images }}{{ item }}"
    dest: "{{ dir_tools }}"
    owner: root
    group: root
    mode: '0755'
    #remote_src: yes
    force: yes
  with_items:
    - '{{file_openshift_installer}}'
    - '{{file_oc}}'
  tags:
    - rerun

# 22.09.2020 - Anpassung: der OC-Client und der OpenShift-Installer werden auf dem Bastion-Host entpackt
- name: "58 - Entpacke OC-Client und Openshift-install-Client"
  unarchive:
    src: "{{ dir_tools }}{{ item }}"
    dest: "{{ dir_tools }}"
    remote_src: yes
  with_items:
    - '{{ file_openshift_installer }}'
    - '{{ file_oc }}' 
  tags:
    - rerun


- name: "59 - Copy kubectl to /usr/local/bin/"
  copy:
    src: "{{ dir_tools }}kubectl"
    dest: "/usr/local/bin/kubectl"
    mode: '0755'
    remote_src: yes
    force: yes
  tags:
    - rerun

- name: "60 - Copy oc to /usr/local/bin/"
  copy:
    src: "{{ dir_tools }}oc"
    dest: "/usr/local/bin/oc"
    mode: '0755'
    remote_src: yes
    force: yes
  tags:
    - rerun

- name: "61 - Copy openshift-install to /usr/local/bin/"
  copy:
    src: "{{ dir_tools }}openshift-install"
    dest: "/usr/local/bin/openshift-install"
    mode: '0755'
    remote_src: yes
    force: yes
  tags:
    - rerun

- name: "62 - Copy pull-secret-original to '{{ dir_cluster }}'"
  copy: 
    src: "{{pull_secret}}"
    dest: "{{ dir_cluster }}{{ pull_secret_file_name }}" 
    owner: root
    group: root
    mode: '0644'
    #remote_src: yes
    force: yes
  tags:
    - rerun
