---
- name: "73 - Allow incoming connections to the tftp service in the firewall"
  firewalld:
    service: tftp
    permanent: yes
    state: enabled
  tags:
    - rerun


- name: "74 - Copy pxelinux.0 and menu.c32 to '{{ dir_tftp_root }}'"
  copy:
    src: "/usr/share/syslinux/{{ item }}"
    dest: "{{ dir_tftp_root }}{{ item }}"
    owner: dnsmasq
    group: wheel
    mode: '0644'
    remote_src: "true"
  with_items: 
    - 'pxelinux.0'
    - 'menu.c32'
    - 'ldlinux.c32'
    - 'libutil.c32'
  tags:
    - linuxbootfiles

- name: "75 - Make sure folder '{{ dir_tftp_root }}pxelinux.cfg/' exists"
  file:
    path: "{{ dir_tftp_root }}pxelinux.cfg"
    state: directory
    owner: dnsmasq
    group: wheel
    mode: '0755'
  tags:
    - linuxbootfiles

# Hinweis !!!

#Diese Aufgaben sollte bei Erstellen der Core-OS-VM-Erstellung mit Terraform ausgeführt werden
# damit die MAC-Adressen verwendet werden können. 
# - name: "34 - Render pxelinux.cfg from templates for masters"
#   template:
#     src: ../99-jinja-templates/pxe/pxelinux.cfg.j2
#     dest: "{{ dir_tftp_root }}pxelinux.cfg/01-{{ item.mac | regex_replace(':','-') }}"
#     owner: dnsmasq
#     group: wheel
#     mode: '0755'
#   vars: 
#     ignition_file: master.ign
#   with_items: "{{ masters }}"

# - name: "35 - Render pxelinux.cfg from templates for workers"
#   template:
#     src: ../99-jinja-templates/pxe/pxelinux.cfg.j2
#     dest: "{{ dir_tftp_root }}pxelinux.cfg/01-{{ item.mac | regex_replace(':','-') }}"
#     owner: dnsmasq
#     group: wheel
#     mode: '0755'
#   vars: 
#     ignition_file: worker.ign
#   with_items: "{{ workers }}"

# - name: "36 - Render pxelinux.cfg from templates for bootstrap"
#   template:
#     src: ../99-jinja-templates/pxe/pxelinux.cfg.j2
#     dest: "{{ dir_tftp_root }}pxelinux.cfg/01-{{ item.mac | regex_replace(':','-') }}"
#     owner: dnsmasq
#     group: wheel
#     mode: '0755'
#   vars: 
#     ignition_file: bootstrap.ign
#   with_items: 
#     - "{{ bstrp }}"

- name: "76 - Start and enable HTTP server"
  service:
    name: httpd
    state: started
    enabled: yes
  tags:
    - rerun

# 21.09.2020 - New Feature to backup the TFTP-Folder-Content
- name: "77 - Backup TFTP-Folder to /opt/sva/backup"
  command: cp -r  "{{ dir_tftp_root }}" "{{ dir_backup_tftp }}"
  tags:
    - rerun
