---
- name: "Installation and Configuration of a central-installation-vm"
  hosts: 127.0.0.1
  gather_facts: "false"
  vars_files:
    - "../vars/vars.yaml"
  tasks:
    - name: "01 - Install necassary software programs"
      become: "true"
      yum:
        name:
          - epel-release
          - centos-release-ansible-29.noarch
          - ansible
          - git
          - sshpass
          - wget.x86_64
          - jq.x86_64
          - podman.x86_64
          - skopeo.x86_64
          - nfs-utils.x86_64
          - unzip
        state: "present"

# Create Working-Directories
    - name: "02 --- Create Working-Directories"
      file:
        path: "{{ item }}"
        state: "directory"
        recurse: "true"
        group: "wheel"
        mode: "0775"
      with_items:
        - "{{ dir_root }}"
        - "{{ dir_terraform }}"
        - "{{ dir_tools }}"
        #- "{{ dir_pi_home }}git"
        
# Download terraform software from internet    
    - name: "03 - Download terraform"
      get_url:
        url: "{{ download_tf }}"
        dest: "{{ dir_terraform }}"

# Download terraform vSphere-Provider-Plugin from internet
    - name: "04 - Download terraform vSphere-Provider-Plugin"
      get_url:
        url: "{{ download_tf_vsphere_plugin }}"
        dest: "{{ dir_terraform_vsphere_plugin }}"

# Extraction of zip-archive
    - name: "05 - Entpacken von terraform"
      unarchive:
        src: "{{ dir_terraform }}terraform_{{ tf_version }}_linux_amd64.zip"
        dest: "{{ dir_tools }}"
        remote_src: "true"

# Make Terraform executable >> copy to /usr/local/bin/terraform
    - name: "06 - Terraform nach /usr/bin kopieren und ausführbar machen"
      become: "true"
      copy:
        src: "{{ dir_tools }}terraform"
        dest: "/usr/local/bin/terraform"
        mode: "0775"
        remote_src: "true"

# Create SSH-Key for root-user
#    - name: "07 - Create SSH-Key for root-user"
#      become: "true"
#      raw: "ssh-keygen -q -t rsa -N '' -f /root/.ssh/id_rsa <<<y 2>&1 >/dev/null"

# Copy SSH-Key to localhost
#    - name: "08 - SSH-COPY-ID"
#      become: "true"
#      raw: "sshpass -f rootpassword ssh-copy-id -i /root/.ssh/id_rsa -o StrictHostKeyChecking=no root@localhost"

# Create User pi
    - name: "09 - Create User pi"
      user:
        name: "pi" 
        group: "wheel"
        shell: "/bin/bash"
        password: "{{'Test1234' | password_hash('sha512', '')}}"
        generate_ssh_key: "true" 
        ssh_key_bits: "2048"
        ssh_key_file: ".ssh/id_rsa"

# Create Working-Directories for User pi
    - name: "09a --- Create Working-Directories for user pi"
      become: "true"
      become_user: "pi"
      file:
        path: "{{ item }}"
        state: "directory"
        recurse: "true"
        group: "wheel"
        #mode: "0775"
      with_items:
        - "{{ dir_pi_home }}git"

# Add right to wheel in sudoers.d
    - name: "10 - add wheel to sudoers.d"
      become: "true"
      raw: "echo '%wheel        ALL=(ALL)       NOPASSWD: ALL' > /etc/sudoers.d/wheel"

# Create Working-Directories for User pi
    - name: "11 --- Create Git-Directory for User PI"
      file:
        path: "{{ dir_pi_home }}git"
        state: "directory"
        owner: "pi"
        group: "wheel"

# Clone Github-Repo automation... to /home/pi/git/ Directory and set permissions for user pi and group wheel
    - name: "12 - Clone Github-Repository https://github.com/Patthecat249/automated-openshift-installation.git"
      git:
        repo: "https://github.com/Patthecat249/automated-openshift-installation.git"
        dest: "{{ dir_pi_home }}git/automated-openshift-installation/"
        clone: "true"
        update: "true"

# chown -R pi:wheel /home/pi/git
    - name: "13 - Change Owner and Group of {{ dir_pi_home }}git"
      file:
        path: "{{ dir_pi_home }}git"
        owner: "pi"
        group: "wheel"
        mode: "0664"
        recurse: "true"

# Do task as pi: ssh-copy-id
    - name: "14 - ssh-copy-id as user-pi"
      become: "true"
      become_user: "pi"
      raw: "ssh-copy-id -o StrictHostKeyChecking=no pi@pi"
...
