---
- name: "Installation and Configuration of a central-installation-vm"
  hosts: all
  gather_facts: "false"
  vars_files:
    - "../vars/vars.yaml"
  tasks:
    - name: "01 - Install software"
      yum:
        name:
          - epel-release
          - wget
          - jq
          - podman
        state: "present"
...
